server:
  port: 8887

spring:
  thymeleaf:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    content-type: text/html
    cache: false
    template-resolver-order:

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://10.254.23.58:8761/eureka/
  instance:
    prefer-ip-address: true


#请求处理的超时时间
ribbon.ReadTimeout: 10000
#请求连接的超时时间
ribbon.ConnectTimeout: 10000