server:
  port: 8063


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.94.159.51:3306/sytest?useSSL=false&&characterEncoding=utf-8
    username: root
    password: 1qaz@wsx?Z


eureka:
  client:
    serviceUrl:
      defaultZone: http://47.94.159.51:8761/eureka/
  instance:
    prefer-ip-address: true