server:
  port: 8063


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.104.19.240:3306/tp_xzh?useSSL=false&&characterEncoding=utf-8
    username: smartcontent
    password: QWE!@#ido85


eureka:
  client:
    serviceUrl:
      defaultZone: http://10.254.23.58:8761/eureka/
  instance:
    prefer-ip-address: true