server:
  port: 8063


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.254.23.60:3306/test?useSSL=false&&characterEncoding=utf-8
    username: root
    password: 1234


eureka:
  client:
    serviceUrl:
      defaultZone: http://10.254.23.58:8761/eureka/
  instance:
    prefer-ip-address: true